# Generated by Django 3.2.8 on 2023-02-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='')),
                ('judul', models.CharField(blank=True, max_length=200, null=True)),
                ('nama', models.CharField(max_length=50, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('deskripsi', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
                ('gambar', models.ImageField(upload_to='')),
                ('judul', models.CharField(blank=True, max_length=200, null=True)),
                ('deskripsi', models.CharField(blank=True, max_length=500, null=True)),
                ('pembayaran', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('pengerjaan', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
