# Generated by Django 3.2.8 on 2023-02-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='jasa',
            name='deskripsi',
        ),
        migrations.AlterField(
            model_name='jasa',
            name='gambar',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
