# Generated by Django 3.2.8 on 2023-02-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_auto_20230227_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='deskripsi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jasa',
            name='deskripsi',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
