# Generated by Django 3.2.8 on 2023-02-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0003_auto_20230227_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasa',
            name='deskripsi',
            field=models.TextField(blank=True),
        ),
    ]
