# Generated by Django 3.2.8 on 2023-02-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0004_alter_jasa_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='deskripsi',
            field=models.TextField(blank=True),
        ),
    ]
