# Generated by Django 3.2.8 on 2023-03-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0005_alter_blog_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasa',
            name='gambar',
            field=models.ImageField(default='images/default.png', upload_to='static/'),
        ),
    ]
