# Generated by Django 3.2.8 on 2023-03-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0006_alter_jasa_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasa',
            name='gambar',
            field=models.ImageField(default='images/default.png', upload_to='media/'),
        ),
    ]
